### ISSUE TITLE
Соответствие дизайну (max 20%):

### ISSUE THREAD

**Issue by OlegZnamenskii** [OlegZnamenskii/html_group_8_homework_34_Oleg_Znamenskii#5]
Очень много несоответствий дизайну -10

**Comment by OlegZnamenskii** [comment]
поправил мелкие косяки

**Comment by tsvetkovamaria** [comment]
А крупные косяки остались http://prntscr.com/eqn7hl http://prntscr.com/eqn7k7 http://prntscr.com/eqn7o6 http://prntscr.com/eqn7rw
